#!/bin/sh
#
#   00-header - create the header of the MOTD
#
[ -r /etc/lsb-release ] && . /etc/lsb-release
if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
        # Fall back to using the very slow lsb_release utility
        DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi
UPDATES=$(cat /etc/update-motd.d/available_updates.log)
echo "\033[1;32m
   .~~.   .~~.
  '. \ ' ' / .'\033[49m
\033[1;31m   .~ .~~~..~.		$DISTRIB_DESCRIPTION $(uname -r)	
  : .~.'~'.~. :		Available updates: $UPDATES
 ~ (   ) (   ) ~
( : '~'.~.'~' : )
 ~ .~ (   ) ~. ~
  (  : '~' :  )
   '~ .~~~. ~'
       '~'\033[49m
"
# Fallback to distro's default colours
printf "\033[0;39m\033[49m"
